version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=ecommerce
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"

volumes:
  postgres:
  pgadmin:
